### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by egoist** [vue-play/vue-play#11]
Example is from react-storybook

<img width="434" alt="2016-10-11 10 51 26" src="https://cloud.githubusercontent.com/assets/8784712/19275132/4d778d6c-9005-11e6-9a82-153cad1471d5.png">

**Comment by egoist** [comment]
| shortcuts | description |
| --- | --- |
| <kbd>cmd shift k</kbd> | toggle full window mode (toggle all panels) |
| <kbd>cmd shift l</kbd> | toggle left panel |
| <kbd>cmd shift d</kbd> | toggle down panel |
| <kbd>shift ←</kbd> | previous playspot |
| <kbd>shift →</kbd> | next playspot |

**Comment by just-be-dev** [comment]
I'm going to try to tackle this one.

**Comment by just-be-dev** [comment]
For the full window mode, what do you want the default to be? So, if one panel is open and one is closed what do you do? Close the open one? Open the closed one?

**Comment by egoist** [comment]
> Close the open one? Open the closed one?

👍🏻 Exactly. But not open all the closed ones, just open the previously closed ones by entering full window mode 😅

**Comment by just-be-dev** [comment]
... I think I get it... It's pretty easy to change regardless. 

This PR turned out to be a LOT more work than I thought it would be...

**Comment by egoist** [comment]
lol, do you use any 3rd-party lib? like mousetrap

**Comment by just-be-dev** [comment]
For this PR? I haven't added any dependencies for this.

**Comment by just-be-dev** [comment]
OKAY! I have working keybindings! It's not completely done yet (have to hook up changing the playspot), but overall it's working. I did lots of things. Please take a look. 

Also, is there someway we can talk more directly? Would be easier to get feedback.

**Comment by egoist** [comment]
- [x] feature
- [ ] doc

**Comment by just-be-dev** [comment]
I think we should add a pop up similar to what react-storybook has. I tinkered with it a little, but I didn't really get anything I liked. Maybe you'll have better luck.
