### ISSUE TITLE
README needs more fancy gifs

### ISSUE THREAD

**Issue by mickdekkers** [vue-play/vue-play#12]
A high-quality gif of vue-play in use, similar to [react-storybook's README](https://github.com/kadirahq/react-storybook#react-storybook---) would be a great way to get people interested.

**Comment by egoist** [comment]
I will add it later.

**Comment by egoist** [comment]
eh, I added a simple gif preview, though it's not so high-quality, I will use a better one when we have hot reloading support for js files.
