### ISSUE TITLE
Dev build doesn't work due to several missing dependencies. 

### ISSUE THREAD

**Issue by just-be-dev** [vue-play/vue-play#13]
I'm about to put in a PR to track this, but here're the reproduction steps
1. `clone https://github.com/vue-play/vue-play`
2. `cd vue-play`
3. `yarn`
4. `yarn run build`

Pretty much the steps I took and it failed.

Looks like there are only two issues. `vbuild` isn't listed as a dev dependency and the version of `vue` needs to be updated.

**Comment by zephraph** [comment]
First failure (due to missing vbuild): 
![image](https://cloud.githubusercontent.com/assets/3087225/19500373/705c73be-956a-11e6-99a1-33a19f5b11cc.png)

**Comment by egoist** [comment]
Close on #14
