### ISSUE TITLE
Example should run in dev mode

### ISSUE THREAD

**Issue by just-be-dev** [vue-play/vue-play#16]
A few issues here. 

There should be a command to run the example (to be able to verify changes). The `surge` command seems to do something like that, but I have no idea what `surge` is. 

I used a snippet of `surge` to accomplish this, but it doesn't actually work. 

``` javascript
// scripts
{
  "example": "vue-play playspot/play.js"
}
```

If I run that I get this error

```
ERROR in multi main
Module not found: Error: Can't resolve '/Users/<user>/.yarn-config/global/node_modules/vue-play-cli/node_modules/webpack-hot-middleware/client' in '/Users/<user>/Git/vue-play'
 @ multi main

ERROR in multi main
Module not found: Error: Can't resolve 'vue-play/dist/vue-play.css' in '/Users/<user>/Git/vue-play'
 @ multi main
```

Note that I _have_ built and `/Users/<user>/Git/vue-play/dist/vue-play.css` exists, but it looks like it's checking for `vue-play/vue-play/dist`

**Comment by egoist** [comment]
How did you install `vue-play-cli`?

**Comment by egoist** [comment]
If you install it from npm it will insert `vue-play/dist/vue-play.css` to entry while building, but apparently `vue-play` is not installed in the example, it's using the source files in `./src`.

Currently I use https://github.com/vue-play/vue-play-cli/blob/master/lib/make-config.js#L95 to check if it should insert `vue-play/dist/vue-play.css`

**Comment by egoist** [comment]
For the `webpack-hot-middleware` error, it seems `/Users/user/.yarn-config/global/node_modules/vue-play-cli/node_modules` will be empty if it's installed with yarn 😰 that's a bit tricky to handle

**Comment by egoist** [comment]
Development section updated https://github.com/vue-play/vue-play#development
