### ISSUE TITLE
Build a plugin system

### ISSUE THREAD

**Issue by just-be-dev** [vue-play/vue-play#18]
As mentioned in #6 it would nice to have a plugin system. 

There're a few things that I can think of that this would entail
- allowing the registration of a new tabbed widget
- allowing the override of the main render window component
- allowing the outside triggering of currently defined actions (meaning we'd need good docs on those)
- potentially allowing for themes or customization of the app shell (might be outside the scope of this ticket)

**Comment by kazupon** [comment]
we might refer to react storybook addon API. 😉 
https://storybooks.js.org/docs/react-storybook/addons/api/
