### ISSUE TITLE
Resize pane

### ISSUE THREAD

**Issue by egoist** [vue-play/vue-play#2]
The sidebar and console should be resizable.

**Comment by egoist** [comment]
Thanks for @QingWei-Li 's work, resize pane feature has landed in `vue-play@0.1.10`

**Comment by egoist** [comment]
@QingWei-Li but there's still an issue, if you drag really fast you can't drag it to the end:

![http://g.recordit.co/uswI4mWF2Q.gif](http://g.recordit.co/uswI4mWF2Q.gif)

Is it the issue of mousemove? or maybe use drag event is better?

**Comment by QingWei-Li** [comment]
I will check it tomorrow.
