### ISSUE TITLE
Use vbuild in vue-play-cli

### ISSUE THREAD

**Issue by egoist** [vue-play/vue-play#21]
`vue-play-cli` has many overlapping functionalities with `vbuild`, but `vbuild` is much more powerful.

The things `vbuild` lacks comparing to `vue-play-cli` are:
- vbuild does not insert 'vue-play/dist/vue-play.css' to entry
- vbuild does not extend your custom webpack config https://github.com/egoist/vbuild/issues/29

**Comment by just-be-dev** [comment]
Won't this make it really heavy? I mean, I like the idea, just asking.

**Comment by egoist** [comment]
@zephraph I don't know, if only consider the dependencies, `vue-play-cli` is already very heavy 😂

No matter whether we use `vbuild` in `vue-play-cli`, I think I will move some rarely used features (like browser-sync) to a separate package, maybe `vbuild-addons` 🤔

By combining https://github.com/egoist/vbuild/issues/29 and https://github.com/webpack-flow/webpack-flow
