### ISSUE TITLE
adding stylus plugins in play.config.js

### ISSUE THREAD

**Issue by jfcieslak** [vue-play/vue-play#22]
Hi, I have a bit of a problem with configuring `play.config.js`
I would like to use stylus on templates, with 2 plugins (nib and rupture). The plugins is where it fails. in my normal `webpack.base.conf.js` I just require the modules for `nib` and `rupture`, and then add the following to `module.exports`:

```
    stylus: {
        use: [nib(), rupture()]
    },
```

But this doesn't seem to work when I add it to `play.config.js`. I get the build error:

```
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-b4c98aaa&scoped=true!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Hello.vue
Module build failed: Error: /Users/franz/Sites/vue-play-app/src/assets/styles/component.styl:1:9
   1| @import 'nib'
--------------^
   2| @import 'rupture'
   3| @import 'imports/mixins'
   4| @import 'imports/variables'

failed to locate @import file nib.styl
```

**So: Is there a way to add plugins to stylus, when compiling with vue-play?**
Thanks!

**Comment by egoist** [comment]
Can you provide your `webpack.base.conf.js` for me to repro?

If you're using your own webpack config, alternatively you can drop `vue-play-cli` and use `webpack-dev-server` or custom server script. The only thing you really need is `vue-play`.

**Comment by jfcieslak** [comment]
My `webpack.base.conf.js` looks like this.

```
var path = require('path')
var config = require('../config')
var utils = require('./utils')
var nib = require('nib')
var rupture = require('rupture')
var projectRoot = path.resolve(__dirname, '../')

var env = process.env.NODE_ENV
// check env & config/index.js to decide weither to enable CSS Sourcemaps for the
// various preprocessor loaders added to vue-loader at the end of this file
var cssSourceMapDev = (env === 'development' && config.dev.cssSourceMap)
var cssSourceMapProd = (env === 'production' && config.build.productionSourceMap)
var useCssSourceMap = cssSourceMapDev || cssSourceMapProd

module.exports = {
    entry: {
        app: ['./src/main.js', 'vue-play/dist/vue-play.css']
    },
    output: {
        path: config.build.assetsRoot,
        publicPath: process.env.NODE_ENV === 'production' ? config.build.assetsPublicPath : config.dev.assetsPublicPath,
        filename: '[name].js'
    },
    resolve: {
        extensions: ['', '.js', '.vue'],
        fallback: [path.join(__dirname, '../node_modules')],
        alias: {
            'vue$': 'vue/dist/vue',
            'src': path.resolve(__dirname, '../src'),
            'assets': path.resolve(__dirname, '../src/assets'),
            'components': path.resolve(__dirname, '../src/components')
        }
    },
    resolveLoader: {
        fallback: [path.join(__dirname, '../node_modules')]
    },
    module: {
        preLoaders: [
            {
                test: /\.vue$/,
                loader: 'eslint',
                include: projectRoot,
                exclude: /node_modules/
            },
            {
                test: /\.js$/,
                loader: 'eslint',
                include: projectRoot,
                exclude: /node_modules/
            }
        ],
        loaders: [
            {
                test: /\.vue$/,
                loader: 'vue'
            },
            {
                test: /\.cvue$/,
                loader: 'vue'
            },
            {
                test: /\.js$/,
                loader: 'babel',
                include: projectRoot,
                exclude: /node_modules/
            },
            {
                test: /\.json$/,
                loader: 'json'
            },
            {
                test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
                loader: 'url',
                query: {
                    limit: 10000,
                    name: utils.assetsPath('img/[name].[hash:7].[ext]')
                }
            },
            {
                test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
                loader: 'url',
                query: {
                    limit: 10000,
                    name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
                }
            }
        ]
    },
    eslint: {
        formatter: require('eslint-friendly-formatter')
    },
    vue: {
        loaders: utils.cssLoaders({ sourceMap: useCssSourceMap }),
        postcss: [
            require('autoprefixer')({
                browsers: ['last 2 versions']
            }),
            require('lost')
        ]
    },
    stylus: {
        use: [nib(), rupture()]
    },
}
```

I was trying to add it like so to the `play.config.js`, which i put in the root of my project.

```
var nib = require('nib')
var rupture = require('rupture')

module.exports = {
    // all the cli options can be defined here and:
    browsers: [], // autoprefixer browsers
    babel: {}, // override babel options
    postcss: [
        require('autoprefixer')({
            browsers: ['last 2 versions']
        }),
        require('lost')
    ]
    loaders: [], // append to current loaders
    stylus: {
        use: [nib(), rupture()]
    },
}
```

Needless to say, I am very far from being a webpack expert. Any help greatly appreciated here!

**Comment by egoist** [comment]
Any luck with `webpack --config webpack.base.conf.js -p` ?

You can't configure stylus in `play.config.js` for now.

**Comment by jfcieslak** [comment]
Not quite, this command launches the server without errors: `vue-play --webpack-config build/webpack.base.conf.js`. But it serves a blank page.

When I do vue-play with default settings and without loading stylus plugins, it renders just fine.

**Comment by jfcieslak** [comment]
If you have time for this and want to check it out, I can post a repo with the project. It's just a dummy with starter component.

**Comment by egoist** [comment]
@jfcieslak sure, please do

**Comment by jfcieslak** [comment]
OK, here it is: https://github.com/jfcieslak/vue-play-app

**Comment by just-be-dev** [comment]
Okay, so here's the issue. 

@jfcieslak you're providing stylus configuration via [this config](https://github.com/jfcieslak/vue-play-app/blob/master/play.config.js#L15-L17). 

@egoist we don't support top level arguments. We'd need an expansion argument around [here](https://github.com/jfcieslak/vue-play-app/blob/master/play.config.js#L15-L17).

We'll need to add an extra key like `moduleConfig` and have it appended to the webpack options. 

---

At least, that's one way to handle it.

**Comment by jfcieslak** [comment]
@zephraph, @egoist: Got it. Actually, what is the main webpack config file that vue-play uses? I am using vue-play within the project scaffolded with official cli, which I assume is going to be a typical case. So perhaps there could be a more straightforward way of using the the standard `build/webpack.dev.conf.js` as a main config? Anyway thanks for looking into this!

**Comment by egoist** [comment]
@jfcieslak check out https://github.com/vue-play/vue-play-cli/blob/master/lib/make-config.js#L105

The only thing that differs from the official webpack template is it adds `vue-play/dist/vue-play.css` to entry and a markdown file loader (which you may rarely use).

**Comment by just-be-dev** [comment]
@jfcieslak does that solution work for you? If so we can likely just close this issue. @egoist we probably need to add some explicit documentation around this.

**Comment by jfcieslak** [comment]
This does explain how webpack config is extended by vue-play, maybe few words in the docs about it would do some good. Thanks!

**Comment by egoist** [comment]
@jfcieslak As version 1.0 was just released, now `vue-play` is to focus on being a framework for demonstrating, leaving the other things to your own bundler setup (vue-play-cli is deprecated). If you are already using the official webpack template, you can almost use the same config but with a different entry to bundle the app.

However if you want a shorthand for bundling `play app`, use [vbuild](https://github.com/egoist/vbuild), I believe it can bundle your components too.

**Comment by jfcieslak** [comment]
OK, cool! will give it a try
