### ISSUE TITLE
Hot Module Replacement not working

### ISSUE THREAD

**Issue by o3oSupport** [vue-play/vue-play#23]
Run the button example.play at http://localhost:5000.It looks good now.
Replace something...

Chrome DevTools:
The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.

**Comment by egoist** [comment]
I guess you should handle hmr yourself? Editing js files does not have built-in hmr support

**Comment by o3oSupport** [comment]
Yeah , i get it.

**Comment by just-be-dev** [comment]
So is there still an issue here or can we close this?

**Comment by o3oSupport** [comment]
Yeah.you can close it.
