### ISSUE TITLE
Remember active tab

### ISSUE THREAD

**Issue by egoist** [vue-play/vue-play#24]
Simply add a state `activeTab` in store, and in component add a computed value:

``` js
computed: {
  active() {
    const activeTab = this.$store.state.layout.activeTab
    const defaultTab = this.readme ? 'readme' : 'console'
    return (activeTab && this[activeTab]) || defaultTab
  }
}
```

**Comment by just-be-dev** [comment]
So, I'm going to tackle this and start paving the way for #18. 

This requires a pretty big refactor of how tabs work overall. I'm going to create a tab model that'll manage both the active state of the bottom panel and which tabs are available to be used.

Wish me luck...
