### ISSUE TITLE
Component filter

### ISSUE THREAD

**Issue by egoist** [vue-play/vue-play#3]
Add a search box to filter components in the sidebar

**Comment by just-be-dev** [comment]
This is a lot harder than expected... Due to the fact that it's a two-tiered list (component and scenario), there technically needs to be two filters and the top one needs to have knowledge of the bottom one.

**Comment by egoist** [comment]
There could be a `select` element to choose searching components or scenarios(default).

> the top one needs to have knowledge of the bottom one

Maybe we don't need this?

**Comment by just-be-dev** [comment]
I think I have an idea of how to accomplish it with a directive... I'll play around with it more sometime later in the week.
