### ISSUE TITLE
Dist files missing from repo/releases?

### ISSUE THREAD

**Issue by casio** [vue-play/vue-play#31]
Hey there,

looking forward to, well, *play* around with this lib : )
However, installing it like `yarn add vue-play/vue-play` and following the examples gives me:
```Module not found: Error: Can't resolve 'vue-play' in '...'```
Same goes for the css import.

Just cloned the repo, ran `npm run build` and then linked it - working nicely now the `./dist` files actually are there.
Are they just missing from the repo?

**Comment by egoist** [comment]
Hi,  you can check out https://unpkg.com/vue-play/ , it seems dist is there.

btw. I wish you can come back in a couple days, this repo is currently under development, and the usage will change a bit (but breaking).

**Comment by casio** [comment]
Thanks for the prompt response!

> btw. I wish you can come back in a couple days

Sure, will do - probably I was just wrong installing from master anyway : )
The commit msgs including new version numbers made me think I could go without waiting for npm updates.

**Comment by egoist** [comment]
`vue-play@2.0.0` released 🎉 no more API breaking changes 😃

Check out https://github.com/vue-play/vue-play#getting-started

**Comment by casio** [comment]
very cool, congrats! 👍 

playing around already.. : )
