### ISSUE TITLE
error in play/app.js

### ISSUE THREAD

**Issue by dweldon** [vue-play/vue-play#32]
I'm trying out rc1 and I'm seeing this error after the call to `app()`:

    Uncaught TypeError: (0 , _app2.default) is not a function

Any idea why might be causing that?

PS: The docs are missing `new` in front of `HtmlWebpackPlugin` in the webpack config.

**Comment by egoist** [comment]
did you use the example code in readme?

**Comment by egoist** [comment]
If you are using `require` it should be `require('vue-play/dist/app').default` or `import 'vue-play/dist/app'`

**Comment by egoist** [comment]
`vue-play-cli` is pretty much done, you can check out https://github.com/vue-play/vue-play-cli

And here's the example entry for webpack. https://github.com/vue-play/vue-play-cli/tree/master/lib/entries

**Comment by dweldon** [comment]
Yeah I used the sample code from the readme. My case may be a little more tricky because I'm integrating it with an existing vue-cli project. Perhaps it's just something silly that I'm missing. I'll give it another try and report back.

**Comment by egoist** [comment]
Closed this, reopen it if you still have this issue.

**Comment by dweldon** [comment]
@egoist I switched to using vue-play-cli and now everything is running. Thanks for all your work on this!
