### ISSUE TITLE
scss error

### ISSUE THREAD

**Issue by sobolevn** [vue-play/vue-play#37]
Hi, I have faced an issue with my component, which styles are written in `scss`. 

Here's the full source of the component itself: https://github.com/wemake-services/vue-material-input/blob/master/src/components/MaterialInput.vue

And the 'example' component source: https://github.com/wemake-services/vue-material-input/blob/master/dev/MaterialModel.vue

My `play/index.js` contents:

```javascript
import { play } from 'vue-play'

import MaterialModel from './MaterialModel.vue'

play(MaterialModel, module)
  .add('v-model', '<MaterialModel></MaterialModel>')
```

Error output:

> [12:41:33] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/vue-material-input ‹master*› » npm run play                                                 130 ↵
> 
> > vue-material-input@1.0.6 play /Users/sobolev/Documents/github/vue-material-input
> > vue-play start
> 
> webpack: wait until bundle finished: 
> webpack built 36b7b27fcdd0e7117400 in 5800ms
> Hash: 36b7b27fcdd0e7117400
> Version: webpack 1.13.3
> Time: 5800ms
>         Asset       Size  Chunks             Chunk Names
> js/preview.js     808 kB       0  [emitted]  preview
>     js/app.js    1.02 MB       1  [emitted]  app
>    index.html  347 bytes          [emitted]  
>  preview.html  351 bytes          [emitted]  
> 
> ERROR in ./play/MaterialModel.vue
> Module not found: Error: Cannot resolve module 'scss' in /Users/sobolev/Documents/github/vue-material-input/play
>  @ ./play/MaterialModel.vue 5:0-168
> 
> ERROR in ./src/components/MaterialInput.vue
> Module not found: Error: Cannot resolve module 'scss' in /Users/sobolev/Documents/github/vue-material-input/src/components
>  @ ./src/components/MaterialInput.vue 5:0-168
> webpack: bundle is now VALID.
> 
> Compiled successfully!
> 
> Vue Play is running at http://localhost:5000

I did not find any neither webpack configuration to edit, nor docs on how to do it.
All versions are latest.

**Comment by egoist** [comment]
I guess it should be `<style lang="sass"></style>` ?

**Comment by sobolevn** [comment]
Yes, `lang="sass"` fixed it. 

Is setting `lang="scss"` a wrong way in general or just with your implementation (never seen any issues before)?

**Comment by egoist** [comment]
eh, I guess `vue-loader` finds the relevant loader by appending `-loader` to the value of `lang` attribute. so in general it's supposed to be `sass` 😅  just wondering why you didn't encounter this issue until now

**Comment by LouiseStroeh** [comment]
Hi. I am experiencing the same as sobolevn. Vue Play works when I am setting `<style lang="sass"></style>`, but this is not an option in the project, I am working on. Is there some way that I can make Vue Play work with `<style lang="scss"></style>`?

**Comment by jaredhobbs** [comment]
i got it working by using the following config:

```
const path = require('path');

module.exports = (config, type) => {
    config.alias = {
        'vue$': 'vue/dist/vue.common.js',
    };
    config.vue.loaders = {
        scss: 'vue-style-loader!css-loader!sass-loader', // <style lang="scss">
        sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax', // <style lang="sass">
    };
    return config;
};
```

**Comment by andreasvirkus** [comment]
@jaredhobbs did you add that file to your `config.js` file or as a separate webpack config under `config/`?

**Comment by jaredhobbs** [comment]
it's what I use as my webpack config: `vue-play start --wc .play.config.js` where `.play.config.js` is the file above
