### ISSUE TITLE
Calling Vue.use

### ISSUE THREAD

**Issue by michaelmior** [vue-play/vue-play#39]
How can I call `Vue.use` (or `Vue.component`) to register other things needed to test my components?

**Comment by egoist** [comment]
To register components:

```js
module.exports.components = {
  MyButton
}
```

In fact, this would also work:

```js
import Vue from 'vue'

Vue.use //... just like a regular app
```

**Comment by michaelmior** [comment]
@egoist Thanks for clarifying. I guess I was wondering if there was some place in particular this was intended to happen. putting this in `play/index.js` does the trick though. Thanks!
