### ISSUE TITLE
[feature request] Display demo source code

### ISSUE THREAD

**Issue by QingWei-Li** [vue-play/vue-play#4]
很棒的项目！
是否考虑加入显示源代码的功能，或者添加 Markdown？这样就可以做为一个生成组件文档工具啦。

**Comment by egoist** [comment]
欢迎 PR 😂

**Comment by egoist** [comment]
想实现可以这样，不过这样示例代码和用来测试的组件代码要写两次感觉有点啰嗦 😅

``` jsx
play({
  Button: {
    'with text': {
      sample: '<button>text</button>',
      render(h) {
        return <button>text</button>'
      }
    }
  }
})
```

**Comment by QingWei-Li** [comment]
是的，不过也无妨。主要是能添加描述信息，顺带加上源码，而且个人感觉示例代码用 vue template 语法居多，所以示例代码和测试组件代码写法可能会不一样。

**Comment by egoist** [comment]
A simple sample code implementation.

<img width="346" alt="2016-10-08 11 47 21" src="https://cloud.githubusercontent.com/assets/8784712/19214280/95550eb2-8db1-11e6-83e1-8c928cafb749.png">

 或许再加个 README 选项传入 markdown。

**Comment by QingWei-Li** [comment]
~~还在纠结 markdown 要怎么写比较好看。~~

~~\- 如果是传字符串的话，多行的字符串就会用 template string, 但是这样反引号就和 markdown 里的反引号语法冲突了，只能用 \`~~

``` javascript
{
  markdown: `
    \`\`\`code
    <my-button />
    \`\`\`
 `
}
```

~~\- 用之前的做法涉及多行的话就用 /，但是感觉好麻烦~~

`````` text
{
  markdown: '/
  ```code/
  <my-button />/
  ```/
  '
}
``````

~~\- 或者写一个 babel 插件？😂~~

代码就写到 sample 里好了... 加一个 markdown 选项传描述信息

**Comment by egoist** [comment]
babel 插件这里怎么用，要不然 markdown 就放在单独的文件用比如 markdown-loader 什么的引入 233

**Comment by QingWei-Li** [comment]
独立的 markdown 文档好像也挺不错，标题对应起来就好了。

**Comment by egoist** [comment]
搞事情，弄个 play-loader 233

``` html
<script>
export default {
  render(h) {
    <ComponentToPlay />
  }
}
</script>

<example>
  <!-- 这个组件这样用 -->
  <component-to-play></component-to-play>
</example>

<readme>
   描述 233
</readme>
```

**Comment by egoist** [comment]
现在支持用 template 了，用 template 的话就不用写 example。 https://github.com/egoist/vue-play/issues/7
