### ISSUE TITLE
Uncaught ReferenceError: _h is not defined

### ISSUE THREAD

**Issue by dweldon** [vue-play/vue-play#40]
Everything works fine with:

```
vue@2.1.4 
vue-template-compiler@2.1.4
vue-play@2.1.1
vue-play-cli@1.0.4
```

However, when I upgrade vue and vue-template-compiler to 2.1.5, nothing renders and I get the following in the console:

```
[Vue warn]: Error when rendering component <home>
Uncaught ReferenceError: _h is not defined
```

Is this just me, or is it failing for anyone else?

**Comment by egoist** [comment]
um.. vue-template-compiler@2.1.5 renamed `_h` to `_c` and we were using `2.1.3` to build vue-play 😂 will fix.

Related to https://github.com/vuejs/vue/commit/4b51ad048306367a6fb6fbee7445e086d855f31e

**Comment by egoist** [comment]
Upgrade to `2.2.0` would fix.
