### ISSUE TITLE
Using template strings

### ISSUE THREAD

**Issue by matteodem** [vue-play/vue-play#42]
I tried using template strings like this:

```js
play(MyButton, module)
  .name('my-other-button')
  .displayName('Show off my cute button')
  .add('with text', '<my-other-button>text</my-other-button>')
```

But I get following error:

```
VM6588:519 [Vue warn]: You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build. 
(found in anonymous component - use the "name" option for better debugging messages.)
```

Any idea on how to resolve this? Would love to get started on writing some ui components

**Comment by egoist** [comment]
use the `--standalone` option if you're using vue-play-cli

check out http://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build for more details.

**Comment by matteodem** [comment]
Thanks! I think it'd be helpful to put that here https://github.com/vue-play/vue-play#register-components. Can create a small PR if you want me to.

**Comment by egoist** [comment]
@matteodem thanks, please do 😀
