### ISSUE TITLE
Display source code of .vue files in the Example tab

### ISSUE THREAD

**Issue by carlmathisen** [vue-play/vue-play#45]
Hi guys,

Thank you for a great project! It was one of the reasons why we could make the switch from React to Vue in one of our products :)

One issue though, I am trying to provide full .vue file examples in our vue-play configuration. Like so:

```
import ButtonWithText from './ButtonWithText.vue'

play('Button', module)
  .add('with text', ButtonWithText)
```

Looking at the source code, vue-play can read the example code automatically from the `template` string property, or the custom `example` property. `template` doesn't really work in this case, since .vue files are processed differently. Also, I would like to display the entire .vue file source code, not just the template, like in this screenshot:

![vue-play-vue-file](https://cloud.githubusercontent.com/assets/380661/21974951/10f845c8-dbca-11e6-83fe-ac2d8550cb2d.png)

I tried using `raw-loader` for Webpack to put the contents of the file into the `example` property:
```
import raw from 'raw-loader!./WithText.vue';
ButtonWithText.example = raw;
```
... but that would just load a compiled version of the .vue file, which makes total sense since `vue-loader` is in the mix too.

Any tips on how to solve this?

**Comment by egoist** [comment]
try `import raw from '!raw-loader!./WithText.vue';`

**Comment by carlmathisen** [comment]
Thank you, that worked perfectly!

I'm trying to think of a way to implement this directly in `vue-play` and create a PR - it would be cool with the `example` property auto-populating itself if  `add(... value)` was a vue file.

Since all imports in ES6 needs to be static, I can't see how `vue-play` itself can load the raw contents dynamically through webpack.

**Comment by egoist** [comment]
> it would be cool with the example property auto-populating itself if add(... value) was a vue file.

this is sure possible, look forward to your PR 😄
