### ISSUE TITLE
Error while trying the process from readme

### ISSUE THREAD

**Issue by pulkitnandan** [vue-play/vue-play#51]
Hi,

I have been trying to use vue-play and followed first 10 lines as per readMe but it fails with following error log

> webpack: wait until bundle finished: 
> webpack built 32d07c8a182557145ebd in 2859ms
> Hash: 32d07c8a182557145ebd
> Version: webpack 1.14.0
> Time: 2859ms
>         Asset     Size  Chunks             Chunk Names
> js/preview.js   986 kB       0  [emitted]  preview
>     js/app.js  1.37 MB       1  [emitted]  app
>    index.html  1.93 kB          [emitted]  
>  preview.html  1.93 kB          [emitted]  
> 
> ERROR in   TypeError: Cannot read property '0' of undefined
>   
>   - ExternalModuleFactoryPlugin.js:18 ExternalModuleFactoryPlugin.<anonymous>
>     [unistore]/[webpack]/lib/ExternalModuleFactoryPlugin.js:18:38
>   
>   - NormalModuleFactory.js:159 
>     [unistore]/[vue-play-cli]/[webpack]/lib/NormalModuleFactory.js:159:3
>   
>   - Tapable.js:75 NormalModuleFactory.applyPluginsAsyncWaterfall
>     [unistore]/[vue-play-cli]/[tapable]/lib/Tapable.js:75:69
>   
>   - NormalModuleFactory.js:144 NormalModuleFactory.create
>     [unistore]/[vue-play-cli]/[webpack]/lib/NormalModuleFactory.js:144:8
>   
>   - Compilation.js:356 Compilation.process [as _addModuleChain]
>     [unistore]/[vue-play-cli]/[webpack]/lib/Compilation.js:356:16
>   
>   - Compilation.js:424 Compilation.process [as addEntry]
>     [unistore]/[vue-play-cli]/[webpack]/lib/Compilation.js:424:7
>   
>   - SingleEntryPlugin.js:24 Compiler.compiler.plugin
>     [unistore]/[webpack]/lib/SingleEntryPlugin.js:24:16
>   
>   - Tapable.js:107 Compiler.applyPluginsParallel
>     [unistore]/[vue-play-cli]/[tapable]/lib/Tapable.js:107:14
>   
>   - Compiler.js:394 Compiler.compile
>     [unistore]/[vue-play-cli]/[webpack]/lib/Compiler.js:394:7
>   
>   - Compiler.js:203 Compiler.runAsChild
>     [unistore]/[vue-play-cli]/[webpack]/lib/Compiler.js:203:7
>   
>   - compiler.js:70 
>     [unistore]/[html-webpack-plugin]/lib/compiler.js:70:19
>   
>   - debuggability.js:300 Promise._execute
>     [unistore]/[bluebird]/js/release/debuggability.js:300:9
>   
>   - promise.js:481 Promise._resolveFromExecutor
>     [unistore]/[bluebird]/js/release/promise.js:481:18
>   
>   - promise.js:77 new Promise
>     [unistore]/[bluebird]/js/release/promise.js:77:14
>   
>   - compiler.js:69 Object.compileTemplate
>     [unistore]/[html-webpack-plugin]/lib/compiler.js:69:10
>   
>   - index.js:47 Compiler.<anonymous>
>     [unistore]/[html-webpack-plugin]/index.js:47:40
>   
> 
> 
> ERROR in   TypeError: Cannot read property '0' of undefined
>   
>   - ExternalModuleFactoryPlugin.js:18 ExternalModuleFactoryPlugin.<anonymous>
>     [unistore]/[webpack]/lib/ExternalModuleFactoryPlugin.js:18:38
>   
>   - NormalModuleFactory.js:159 
>     [unistore]/[vue-play-cli]/[webpack]/lib/NormalModuleFactory.js:159:3
>   
>   - Tapable.js:75 NormalModuleFactory.applyPluginsAsyncWaterfall
>     [unistore]/[vue-play-cli]/[tapable]/lib/Tapable.js:75:69
>   
>   - NormalModuleFactory.js:144 NormalModuleFactory.create
>     [unistore]/[vue-play-cli]/[webpack]/lib/NormalModuleFactory.js:144:8
>   
>   - Compilation.js:356 Compilation.process [as _addModuleChain]
>     [unistore]/[vue-play-cli]/[webpack]/lib/Compilation.js:356:16
>   
>   - Compilation.js:424 Compilation.process [as addEntry]
>     [unistore]/[vue-play-cli]/[webpack]/lib/Compilation.js:424:7
>   
>   - SingleEntryPlugin.js:24 Compiler.compiler.plugin
>     [unistore]/[webpack]/lib/SingleEntryPlugin.js:24:16
>   
>   - Tapable.js:107 Compiler.applyPluginsParallel
>     [unistore]/[vue-play-cli]/[tapable]/lib/Tapable.js:107:14
>   
>   - Compiler.js:394 Compiler.compile
>     [unistore]/[vue-play-cli]/[webpack]/lib/Compiler.js:394:7
>   
>   - Compiler.js:203 Compiler.runAsChild
>     [unistore]/[vue-play-cli]/[webpack]/lib/Compiler.js:203:7
>   
>   - compiler.js:70 
>     [unistore]/[html-webpack-plugin]/lib/compiler.js:70:19
>   
>   - debuggability.js:300 Promise._execute
>     [unistore]/[bluebird]/js/release/debuggability.js:300:9
>   
>   - promise.js:481 Promise._resolveFromExecutor
>     [unistore]/[bluebird]/js/release/promise.js:481:18
>   
>   - promise.js:77 new Promise
>     [unistore]/[bluebird]/js/release/promise.js:77:14
>   
>   - compiler.js:69 Object.compileTemplate
>     [unistore]/[html-webpack-plugin]/lib/compiler.js:69:10
>   
>   - index.js:47 Compiler.<anonymous>
>     [unistore]/[html-webpack-plugin]/index.js:47:40
>   
> 
> webpack: Failed to compile.
> 
> Compiled successfully!
> 
> Vue Play is running at http://localhost:5000

I have generated the boilerplate code using the https://github.com/nuxt/express and tried the harder way as well. Same error is thrown on port 5000.

**Comment by egoist** [comment]
vue-play-cli is using webpack 1, and seems you have webpack 2 and html-webpack-plugin for webpack 2 installed in your project.

**Comment by dweldon** [comment]
@pulkitnandan if you are willing to set it up "the hard way", I'd have a look at issue #44 for a solution.

**Comment by pulkitnandan** [comment]
@dweldon  It doesn't works. same error.

But I did managed to get it work after a package was installed locally without --save-dev, just forgot it's name, also deleted node-modules.

**Comment by rohitcelestial** [comment]
Is there any way to make it work with webpack v1? @egoist Please suggest.

**Comment by egoist** [comment]
Try the new `getplay`: https://github.com/vue-play/vue-play#getting-started

**Comment by pulkitnandan** [comment]
I'm using nuxt 0.9.11 and vue play give following error on yarn play but it did works fine with the latest pull of nuxt-express starter template.

ERROR in   TypeError: Cannot read property 'request' of undefined
  
  - ExternalModuleFactoryPlugin.js:37 handleExternals
    [store]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33
  
  - ExternalModuleFactoryPlugin.js:46 next
    [store]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8
  
  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [store]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7
  
  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [store]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5
  
  - NormalModuleFactory.js:233 
    [store]/[webpack]/lib/NormalModuleFactory.js:233:3
  
  - Tapable.js:196 NormalModuleFactory.applyPluginsAsyncWaterfall
    [store]/[webpack]/[tapable]/lib/Tapable.js:196:70
  
  - NormalModuleFactory.js:217 NormalModuleFactory.create
    [store]/[webpack]/lib/NormalModuleFactory.js:217:8
  
  - Compilation.js:377 Compilation._addModuleChain
    [store]/[webpack]/lib/Compilation.js:377:17
  
  - Compilation.js:455 Compilation.addEntry
    [store]/[webpack]/lib/Compilation.js:455:8
  
  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [store]/[html-webpack-plugin]/[webpack]/lib/SingleEntryPlugin.js:22:15
  
  - Tapable.js:229 Compiler.applyPluginsParallel
    [store]/[webpack]/[tapable]/lib/Tapable.js:229:14
  
  - Compiler.js:469 
    [store]/[webpack]/lib/Compiler.js:469:8
  
  - Tapable.js:131 Compiler.applyPluginsAsyncSeries
    [store]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compiler.js:462 Compiler.compile
    [store]/[webpack]/lib/Compiler.js:462:7
  
  - Compiler.js:266 Compiler.runAsChild
    [store]/[webpack]/lib/Compiler.js:266:7
  
  - compiler.js:70 
    [store]/[html-webpack-plugin]/lib/compiler.js:70:19
  
  - debuggability.js:300 Promise._execute
    [store]/[bluebird]/js/release/debuggability.js:300:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [store]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [store]/[bluebird]/js/release/promise.js:79:10
  
  - compiler.js:69 Object.compileTemplate
    [store]/[html-webpack-plugin]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.<anonymous>
    [store]/[html-webpack-plugin]/index.js:47:40
  
  - Tapable.js:229 Compiler.applyPluginsParallel
    [store]/[webpack]/[tapable]/lib/Tapable.js:229:14
  


ERROR in   TypeError: Cannot read property 'request' of undefined
  
  - ExternalModuleFactoryPlugin.js:37 handleExternals
    [store]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33
  
  - ExternalModuleFactoryPlugin.js:46 next
    [store]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8
  
  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [store]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7
  
  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [store]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5
  
  - NormalModuleFactory.js:233 
    [store]/[webpack]/lib/NormalModuleFactory.js:233:3
  
  - Tapable.js:196 NormalModuleFactory.applyPluginsAsyncWaterfall
    [store]/[webpack]/[tapable]/lib/Tapable.js:196:70
  
  - NormalModuleFactory.js:217 NormalModuleFactory.create
    [store]/[webpack]/lib/NormalModuleFactory.js:217:8
  
  - Compilation.js:377 Compilation._addModuleChain
    [store]/[webpack]/lib/Compilation.js:377:17
  
  - Compilation.js:455 Compilation.addEntry
    [store]/[webpack]/lib/Compilation.js:455:8
  
  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [store]/[html-webpack-plugin]/[webpack]/lib/SingleEntryPlugin.js:22:15
  
  - Tapable.js:229 Compiler.applyPluginsParallel
    [store]/[webpack]/[tapable]/lib/Tapable.js:229:14
  
  - Compiler.js:469 
    [store]/[webpack]/lib/Compiler.js:469:8
  
  - Tapable.js:131 Compiler.applyPluginsAsyncSeries
    [store]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compiler.js:462 Compiler.compile
    [store]/[webpack]/lib/Compiler.js:462:7
  
  - Compiler.js:266 Compiler.runAsChild
    [store]/[webpack]/lib/Compiler.js:266:7
  
  - compiler.js:70 
    [store]/[html-webpack-plugin]/lib/compiler.js:70:19
  
  - debuggability.js:300 Promise._execute
    [store]/[bluebird]/js/release/debuggability.js:300:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [store]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [store]/[bluebird]/js/release/promise.js:79:10
  
  - compiler.js:69 Object.compileTemplate
    [store]/[html-webpack-plugin]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.<anonymous>
    [store]/[html-webpack-plugin]/index.js:47:40
  
  - Tapable.js:229 Compiler.applyPluginsParallel
    [store]/[webpack]/[tapable]/lib/Tapable.js:229:14
  


ERROR in ./~/css-loader?-autoprefixer&sourceMap!./~/postcss-loader?sourceMap!./~/vue-play/dist/app.css
Module build failed: TypeError: Cannot read property 'postcss' of undefined
    at Processor.normalize (/home/rohitn/store/node_modules/postcss/lib/processor.js:136:12)
    at new Processor (/home/rohitn/store/node_modules/postcss/lib/processor.js:51:25)
    at postcss (/home/rohitn/store/node_modules/postcss/lib/postcss.js:73:10)
    at Object.module.exports (/home/rohitn/store/node_modules/postcss-loader/index.js:92:5)
 @ ./~/vue-play/dist/app.css 4:14-126 13:3-17:5 14:22-134
 @ ./~/vue-play/app.js
 @ ./play/app.js
 @ multi play/app.js

 ERROR  Compiling failed!

**Comment by egoist** [comment]
I'm not sure what's going on with this, it would be much better if you can provide a repo
