### ISSUE TITLE
Add a tab for discussions

### ISSUE THREAD

**Issue by egoist** [vue-play/vue-play#6]
This is useful for designers and programmer to discuss about the related component. It should support disqus and duoshuo, etc…

**Comment by just-be-dev** [comment]
Where will the tab go? Inside the... playground? or whatever the component rendering area is called.

**Comment by egoist** [comment]
@zephraph inside the down panel, just add a new tab

**Comment by just-be-dev** [comment]
How do we persist the discussion?

**Comment by egoist** [comment]
@zephraph use disqus or such 😅

**Comment by just-be-dev** [comment]
As per our discussion, I believe this should likely just be closed. It's a great idea, but probably better implemented via a plugin system.
