### ISSUE TITLE
Setting up with Vuetify

### ISSUE THREAD

**Issue by walleXD** [vue-play/vue-play#62]
Hi all, 

[Vuetify](https://vuetifyjs.com/) is a material design component library for vue. I am trying to use it for my project but I am not sure how to use it in conjunction with vue-play to develop my components. What would be the way to do so? 

Thanks alot

**Comment by egoist** [comment]
Hmm, I think nothing special? It's just a framework:

```js
import Vue from 'vue'
import Vuetify from 'vuetify'
 
Vue.use(Vuetify)
```

**Comment by walleXD** [comment]
Ah. 

How do I include the CSS/Stylus files?

**Comment by egoist** [comment]
Same as other vue/webpack project.

**Comment by walleXD** [comment]
I am using nuxt.js with vuetify. So, how would you suggest adding all the appropriate css files? I am not entirely sure about the best way of doing in in vue-play

figured it out 👍 

Just a simple import of the stylus file into the index.js in the play folder does the work
```
import '../styles/app.styl'
```
