### ISSUE TITLE
Use without dependency on poi

### ISSUE THREAD

**Issue by matt-oconnell** [vue-play/vue-play#65]
We are working with an existing codebase that is on an alpha version of Babel 7. Poi currently uses Babel 6, making it incompatible with our current project. It would be very helpful to allow for manual configuration of `vue-play`'s webpack configuration (+ webpack dev server / hot-reloading) without hard-tying it to `poi`.

**Comment by egoist** [comment]
this is all your need for a normal webpack project:

```js
// webpack.config.js
module.exports = {
  entry: {
    app: 'play/app.js',
    preview: 'play/preview.js' // <-- maybe add hot reload support to this entry yourself
  },
  plugins: [
    new HtmlWebpackPlugin({
      chunks: ['app'],
      filename: 'index.html',
      template: 'your-template.html'
    }),
    new HtmlWebpackPlugin({
      chunks: ['preview'],
      filename: 'preview.html',
      template: 'your-template.html'
    })
  ]
}
```

Your template file for `html-webpack-plugin` should have a `<div id="app"></div>` tag since `vue-play` is mounted there.

**Comment by matt-oconnell** [comment]
@egoist Thanks!
