### ISSUE TITLE
Usage with vue-share-components

### ISSUE THREAD

**Issue by hauptrolle** [vue-play/vue-play#66]
Hi,

first of all. Thank you for your nice work!

When I setup a project with [vue-share-components](https://github.com/Akryum/vue-share-components/issues) and then add vue-play with `getplay` the demo of the default test componenten doesn't work. I get the following error:
```
ERROR in ./src/components/Button/Button.vue
Module build failed: TypeError: loader.charAt is not a function
```

If i change`poi` to `vbuild` everything works fine, but I dont have the hot reloading.

I could need some help here ...

**Comment by egoist** [comment]
Upgrade `vue-loader` in your project, it might be out-dated.

**Comment by hauptrolle** [comment]
@egoist Wow. Sometimes it is so easy 😄 
I had vue-loader 10.0.0 installed. With the latest 12.x.x version it works.
Thanks for your fast reply and have a nice weekend.
