### ISSUE TITLE
play.js is not valid JavaScript

### ISSUE THREAD

**Issue by PandaWhisperer** [vue-play/vue-play#7]
I love the idea of doing react-storybook for Vue.js, in fact, just the other day, I had thought about implementing it myself. 

But please, since the goal of Vue.js is replacing React and its JSX nonsense, can we not have unquoted HTML in JavaScript files? Perhaps the test functions could just return a string instead, so that the `play.js` is valid JavaScript and doesn't throw off my linter.

Thanks for your hard work.

**Comment by djyde** [comment]
Actually I prefer using Hyperscript instead.

**Comment by egoist** [comment]
So, now we have a bunch of ways to write the play script:

``` js
play({
  Button: {
    'with jsx'(h) {
      return <button>text</button>
    },
    'with template': '<button>text</button>',
    'with full component': {
       // component properties, like template/render, data, methods
    }
  }
})
```

A good thing of using template is, it will automatically generate example code for the component.
